### ISSUE TITLE
Observation and CDN Cache Invalidation

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#129]
The current cache invalidation (fastly) is only done for github content on repositories where the helix-bot is installed. it doesn't support documents on onedrive or google drive yet. also, it doesn't leverage the observation framework but purges the fastly service directly.

### Goal
The goal of this theme is:
- implement fastly cache invalidation based on the observation framework
- ensure that modification to the github content, onedrive content and google drive content trigger the correct observation events
- create command line tools to setup / manage the observation infrastructure
- (create UI tools to setup / manage the observation infrastructure)
- add automation where possible to automatically setup observation and cache invalidation and indexing

### Overview

see https://github.com/adobe/helix-home/tree/master/docs/observation for the current documentation, which is a bit outdated as it doesn't include the latest changes using the observation message bus.

the architecture is changed as follows:

- the observation triggers are replaced by a message bus (based on https://azure.microsoft.com/en-us/services/service-bus/). 
- the change-listeners (onedrive, google drive, github observation) add the change events to message bus<sup>1</sup>
- for each observed repository, a task-controller action is started as soon as there is work to do.
- for each _subscriber_ action, a task-queue storage table is created. this allows throttled and controlled execution of the actions.
- the task-controller uses the task-queue storage table to manage the tasks execution of the task-actions.

<sup>1</sup>: See question (4) below.

### Triggers / Management
With the openwhisk triggers, we had an easy control mechanism to forward the events to the actions. With the service-bus we need to add tooling to the observation-admin

Example:

"On the 'tripod' namespace, I want to create a observation listener action named 'calculate' that reacts on changes in the `tripodsan/helix-test` repository.

- we create a service bus topic `tripodsan--helix-test--master` (via the observation-admin)
- the user registers his `calculate` action as observation listener
- we create a task-queue `tripod--calculate`

1. on modification, an event with the `tripodsan--helix-test--master` topic is added to the message bus
2. the task-controller is started (how?) in the customers namespace. which reads the message bus and invokes the customers listener actions for each task. (via the tasks-invokers). 

#### General
- [ ] update the observation documentation in https://github.com/adobe/helix-home/tree/master/docs/observation [observation#72](https://github.com/adobe/helix-observation/issues/72)

#### Observation Core
- [ ] add the observation management to the observation-admin action [admin#64](https://github.com/adobe/helix-observation-admin/issues/64)
- [ ] change the observation action to create service-bus events instead of invoking the trigger [observation#73](https://github.com/adobe/helix-observation/issues/73)
- [ ] create a dev-tool/admin to create the observation topic 

#### OneDrive Support
- [ ] create a dev-tool/admin to create onedrive subscriptions (partially done)
- [ ] create some automation to listen on fstab changes and create the subscriptions

#### GoogleDrive Support
- [ ] implement the google-drive listener and send events to the observation queue
- [ ] create a dev-tool/admin to manage what ever the google-drive listener needs
- [ ] create some automation to listen on fstab changes and create the subscriptions

#### Cache Invalidation
- [ ] add an observation listener that invalidates the fastly based on the changes
- [ ] add some tooling that can setup the listener with the correct fastly credentials and subscribe it to the correct topic (probably in helix-bot-action-config)

#### Indexing
- [ ] adding a helix-query.yaml should automatically setup the indexing listeners

## Open Questions

1. As for helix-pages, should the fastly cache automatically be flushed even if no helix-bot is installed on the repository. this might be possible for onedrive/googledrive but not for github changes.

> (@tripodsan): _I think to start with, we can mandate the helix-bot to be present._

2. As for helix-pages, should the indexing be automatically setup? is there a default helix-query.yaml or does it require the helix-bot and an explicit helix-query.yaml

> (@tripodsan): _I think to start with, we can mandate the helix-bot and the helix-query.yaml to be present._

3. How are the task-controllers started? possible solutions:
   - use openwhisk cron to invoke them periodically
   - keep them running idle (min load: 1 invocation per minute)
   - the change listeners _ensure_ that they are running. eg. add code to the `observation` action that can handle this.

4. In the architecture described above, the change listener directly add the events to the service bus. but it might be more practical to do use a common action (the `observation` action). So the change listeners would use the same mechanism as the helix-bot. the disadvantage is, that if the `observation` action fails, the events might get lost.

> (@tripodsan): _I think it would be better to consolidate this using the `observation` action. This might also make the task-controller problem (3) easier to manage._

**Comment by trieloff** [comment]
> 1. As for helix-pages, should the fastly cache automatically be flushed even if no helix-bot is installed on the repository. this might be possible for onedrive/googledrive but not for github changes.

Having the bot installed is a reasonable requirement for getting cache flushes. In places where we can do without the bot (Google and Word), we will of course flush automatically.

**Comment by trieloff** [comment]
> 2. As for helix-pages, should the indexing be automatically setup? is there a default `helix-query.yaml` or does it require the helix-bot and an explicit helix-query.yaml

A default that just extracts page title and path could be useful to have built-in support for `sitemap.xml`

**Comment by tripodsan** [comment]
closing as with helix3 cache flushing is triggered when pages are published.
