### ISSUE TITLE
[h3] Edge Roadmap

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#206]
## Overview

What's needed to transition Helix to a fully redundant edge-compute setup, in the form of an annotated todo list

### Functionality

- [ ] sort out logging
- [ ] enable repo onboarding without redeployment
- [ ] enable mount point updates without redeployment
- [ ] enable IP restrictions without redeployment

> This can be done by fetching the config directly from the Helix Code Bus repos or by replicating the Fastly Edge Dicts to CloudFlare. Both options are worth trying.

### Stretch Functionality

- [ ] port `helix-pipeline-service` from serverless to edge compute

> We have to mind the 1 MB worker size limit in CloudFlare and hope that all native node modules used have polyfills.

### Deployment

- [ ] deploy H3F (Helix 3 on Fastly Compute@Edge) via CI
- [ ] deploy H3C (Helix 3 on Cloudflare Workers) via CI
- [ ] deploy helix-admin to Google
- [ ] deploy helix-pipeline-service to Google

> The goal is to have full redundant backend stacks

### Multi-Cloud

- [ ] mirror Helix Code Bus on Google Cloud Storage
- [ ] mirror Helix Content Bus on Google Cloud Storage
- [ ] mirror Helix Media Bus on Google Cloud Storage
- [ ] mirror Helix Media Bus on S3
- [ ] serve Helix Media on H3F from S3
- [ ] serve H3C from Google

### Testing

- [ ] enable smoke/diff tests for H3F
- [ ] enable smoke/diff tests for H3C

### Monitoring

- [x] create NR monitors for H3F
- [x] create NR monitors for H3C

### Operations

- [x] connect DNS CNAME mapping to monitoring status (automated CDN switch)

**Comment by trieloff** [comment]
One more thought: we should probably agree on quality gates for the edge code to decide when to include them in the stack. @stefan-guggisberg and I can probably discuss for ages which greek letter best describes the quality of a given edge platform, so I'd like to set some metrics that give us an objective comparison.

My suggestion: if an edge platform has less than 2x the error rate and less than 2x median request duration compared to the baseline (H3VCL), it is viable and can be used in production.

**Comment by stefan-guggisberg** [comment]
> My suggestion: if an edge platform has less than 2x the error rate and less than 2x median request duration compared to the baseline (H3VCL), it is viable and can be used in production.

Agreed. We should find a way to compare error rates with same kind of traffic (volume & kind of reqs). And error rates need to be clearly specified. We should only be looking at errors generated by Edge Compute and compare them with Fastly service errors (not sure how can identify these).

**Comment by trieloff** [comment]
The monitoring scripts should cover all request types, maybe port the test harness.

**Comment by trieloff** [comment]
Discussion on achieving multi-cloud storage: https://github.com/adobe/helix-home/discussions/207
